version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/tag-replacer
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Update Greenkeeper lockfile
          command: npm run gk-update
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Upload Greenkeeper lockfile
          command: npm run gk-upload
